# -*- coding: utf-8 -*-
# -----------------------------
# @Author    : 影子
# @Time      : 2026/7/14 15:13
# @Software  : PyCharm
# @FileName  : html_ex.py
# -----------------------------
"""
HTML 导出器
"""
from typing import List, Dict
from .base import BaseExporter


class HTMLExporter(BaseExporter):
    """HTML 表格导出器"""

    def export(self, data: List[Dict], filepath: str, title: str = 'FakerX Data',
               **kwargs):
        if not data:
            return

        flat_data = [self.flatten(row) for row in data]
        headers = list(flat_data[0].keys())

        html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th {{ background-color: #4472C4; color: white; padding: 10px 12px;
              text-align: left; border: 1px solid #ddd; }}
        td {{ padding: 8px 12px; border: 1px solid #ddd; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        tr:hover {{ background-color: #f0f0f0; }}
        .meta {{ color: #888; font-size: 0.85em; margin-bottom: 15px; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="meta">Generated by FakerX | {len(data)} records</div>
    <table>
        <thead>
            <tr>
'''
        for h in headers:
            html += f'                <th>{h}</th>\n'
        html += '            </tr>\n        </thead>\n        <tbody>\n'

        for row in flat_data:
            html += '            <tr>\n'
            for h in headers:
                val = row.get(h, '')
                html += f'                <td>{val}</td>\n'
            html += '            </tr>\n'

        html += '''        </tbody>
    </table>
</body>
</html>'''

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)

    def export_stream(self, generator, filepath: str, title: str = 'FakerX Data',
                      **kwargs):
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        table {{ border-collapse: collapse; width: 100%; }}
        th {{ background-color: #4472C4; color: white; padding: 10px; text-align: left; }}
        td {{ padding: 8px 12px; border: 1px solid #ddd; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <table>
''')

            headers_written = False
            count = 0
            for record in generator:
                flat = self.flatten(record)
                if not headers_written:
                    headers = list(flat.keys())
                    f.write('<thead><tr>')
                    for h in headers:
                        f.write(f'<th>{h}</th>')
                    f.write('</tr></thead><tbody>\n')
                    headers_written = True
                f.write('<tr>')
                for h in headers:
                    f.write(f'<td>{flat.get(h, "")}</td>')
                f.write('</tr>\n')
                count += 1

            f.write(f'''</tbody>
    </table>
    <p>{count} records</p>
</body>
</html>''')
